# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: local
      hooks:
          - id: black
            name: black
            types: [python]
            language: system
            entry: black .
    - repo: local
      hooks:
          - id: isort
            name: isort
            types: [python]
            language: system
            entry: isort .
    - repo: local
      hooks:
          - id: pycln
            name: pycln
            types: [python]
            language: system
            entry: pycln .
    # - repo: local
    #   hooks:
    #       - id: mypy
    #         name: mypy
    #         types: [python]
    #         language: system
    #         entry: mypy .
    #         pass_filenames: false
